### ISSUE TITLE
Dependencies missing for later versions of Debian/Raspbian (particularly Buster) 

### ISSUE THREAD

**Issue by ghost** [Kneesnap/deltarune-circuit-sword#1]
So, I tried out this neat little project because I wanted to see how it worked, but on the latest version of Raspbian, the game complains that it needs libcurl3 and libssl1.0.2. That, ordinarily, wouldn't be an issue, but turns out that those dependencies cannot be obtained through the apt manager on Buster.

Because of this issue, I went through the trouble of manually downloading those packages and neatly put them into the attached archive. I even included a little run script for convenience.

Would you be so kind as to package the contents with the game and update the release?

Thanks.

[Download "Dependencies.tar.gz"](https://github.com/Kneesnap/deltarune-circuit-sword/files/4893393/Dependencies.tar.gz)

**Comment by Kneesnap** [comment]
I can't just take compiled binaries that someone sends me online, so I've grabbed them from my own system.

I've uploaded a new release though, hopefully it works.

**Comment by ghost** [comment]
Fair enough, you know, security risks and all.
But thanks for your help.
