### ISSUE TITLE
Undertale controller inputs

### ISSUE THREAD

**Issue by TheOneAnthony** [Kneesnap/deltarune-circuit-sword#2]
Deltarune works perfectly but loading it with Undertale (while it works) only allows keyboard input while the controller is ignored. i know I have to edit the data to fix this (which  I'm guessing is why you cant distribute it) s, but do you have the code you used for Undertale (the gml scrips that you changed for the controls)  that you used with this for the controller inputs? 

by the way amazing work.

**Comment by TheOneAnthony** [comment]
actually i just realized. could you just make a patch file like .bps patch to turn existing Undertale Data file into the one needed to have working controls?

**Comment by TheOneAnthony** [comment]
that way you would need to worry about any copyright since a .bps would require someone to already have the data file for the game.

**Comment by Kneesnap** [comment]
Unfortunately, UTMT isn't byte-accurate, meaning this patchn would be as
large as the game itself

**Comment by TheOneAnthony** [comment]
ah. I see. makes sense.
how did you get the controls for undertale working then? I was able to find and modify the ones in deltarune easy, but i cant find anything for undertale's file.

**Comment by Kneesnap** [comment]
If I recall, I made functions/scripts and replaced all calls to input
functions with my own functions. It sas annoying, but doable. What I did
was make it check what key it was looking for, and so it would do the
normal keyboard check in the function, but also the gamepad check. That way
I could plug in a keyboard and it would work, but it would also work if I
used the controls. If you prefer, you can also DM me on discord.
Kneesnap#7540

**Comment by TheOneAnthony** [comment]
Thanks. I'll message you when I get home
